const stories={
beads:{tag:'樂齡創作',date:'2026 年 8 月 21 日｜大進廟社區',title:'一顆一顆拼出「吉」祥，長輩動手也動腦',deck:'從手機上的像素圖稿開始，看看學員怎麼拼出「吉」字杯墊。',body:`<p>上午十點，大進廟社區的桌上放著各色拼豆。學員一邊看圖稿，一邊挑顏色、找位置，再把豆子放上底板。大家邊做邊確認圖案，遇到不確定的地方就互相討論。</p><h3>從手機圖稿，走到手心作品</h3><p>課程先用手機介紹像素圖，也示範把照片轉成點陣圖，再調整成底板大小。第一次拼豆的學員先從顏色較少的圖案開始。</p><p>這次大家做的是「吉」字杯墊。學員對照圖稿挑顏色、數位置，再把拼豆逐一排好；放錯位置就得重新確認圖案。</p><h3>小小拼豆，練習專注與手眼協調</h3><p>有人先數好每一排的顏色，有人邊看圖邊放豆子。大家照自己的速度完成作品，也會互相確認位置有沒有放對。</p><blockquote>「很好玩，比較動腦。」問他下次還想不想參加，阿伯馬上回答：「會、會。」</blockquote><p>課程從手機圖稿開始，最後完成可以帶回家的「吉」字杯墊。學員也練習了看圖、配色和排列。</p>`},
nutrition:{tag:'健康生活',date:'2026 年 8 月 20 日｜大坑罟、港邊社區',title:'從餐桌出發，長輩一起破解飲食迷思',deck:'謝侑錠老師帶大家認識六大類食物，並討論平常吃的食物怎麼分類。',body:`<p>營養衛教課分別在大坑罟和港邊社區進行。謝侑錠老師從六大類食物開始說明，也請大家分享平常怎麼買菜、買魚和安排餐點。</p><h3>把營養知識，放回每天的餐桌</h3><p>聊到牛奶時，老師說明鮮奶與保久乳在營養上的差異不大，主要差別是殺菌和保存方式。補充鈣質也可以從芥菜、莧菜等食物攝取。大家也分享買魚的經驗，並討論豆魚蛋肉類的分類。</p><p>老師提醒油炸食物要適量，旁邊的長輩笑著說：「有沒有聽到！」談到水果時，老師也提醒水果不能取代正餐；除了均衡飲食，也要活動身體、攝取足夠蛋白質。</p><h3>在賓果遊戲裡複習，也在分享裡互相提醒</h3><p>最後大家玩賓果，複習六大類食物、鈣質、水果、油脂和肌少症等課堂內容。</p><blockquote>王阿姨想起今天印象最深的內容是「食物有六大類」，也說：「以前都沒有注意這些。」</blockquote><p>課程在大坑罟和港邊各進行一場。長輩透過提問、分享和賓果遊戲，複習六大類食物及課堂提到的營養觀念。</p>`},
ocean:{tag:'海洋文化',date:'2026 年 8 月 20 日｜南方澳',title:'港邊的網，手心的魚',deck:'工作坊以漁網和魚為發想，帶長輩與志工一起製作海洋掛飾。',body:`<p>南方澳漁港常見漁船和漁網，補網也是漁村生活的一部分。這次工作坊以魚和網為題，讓長輩從熟悉的地方景物開始做作品。</p><h3>漁網變身，成為創作的媒介</h3><p>這次工作坊從南方澳熟悉的「網」與「魚」出發。大家用絨線鐵絲（毛根）折出魚尾、塑造魚身，再把剩下的線材一圈圈纏繞；完成小魚後，再與網狀素材結合，慢慢做成海洋掛飾。</p><p>這堂課不是教大家修補漁網，而是用手作認識漁網和魚。網狀素材與毛根成了材料，長輩和志工一邊製作，一邊聊起對南方澳的印象。</p><h3>一起動手，也一起聊起生活</h3><p>志工在旁協助，也和長輩聊魚和補網。有人研究線要怎麼繞，有人做好後展示作品，也有人請身旁的夥伴幫忙。</p><p>製作時需要彎折毛根、纏繞線材，再把素材固定在網上。志工在旁協助，學員也會互相看看彼此做到哪裡。</p><p>完成的掛飾帶有魚和網的樣子，也記下了這堂課大家一起動手的過程。</p>`}
};
const galleries={beads:[['./images/story-beads/image1.png','長輩展示拼豆作品'],['./images/story-beads/image2.jpg','長輩在桌邊專心拼豆'],['./images/story-beads/image3.jpg','長輩低頭排列拼豆'],['./images/story-beads/image4.jpg','社區學員一起參加拼豆課'],['./images/story-beads/image5.jpg','夥伴互相陪伴完成作品']],nutrition:[['./images/story-nutrition/image1.png','長輩一起參與營養課程'],['./images/story-nutrition/image2.jpg','社區課堂中的學員'],['./images/story-nutrition/image3.jpg','長輩專心聽營養分享'],['./images/story-nutrition/image4.jpg','老師介紹日常營養知識'],['./images/story-nutrition/image5.jpg','社區居民一起上課'],['./images/story-nutrition/image6.jpg','營養課程交流時光'],['./images/story-nutrition/image7.jpg','長輩透過賓果遊戲複習'],['./images/story-nutrition/image8.jpg','老師帶領課堂討論'],['./images/story-nutrition/image9.jpg','課堂中的互動與分享']],ocean:[['./images/story-ocean/image1.jpg','學員專注製作海洋掛飾'],['./images/story-ocean/image2.jpg','志工陪伴長輩製作掛飾'],['./images/story-ocean/image3.jpg','志工與學員一起動手'],['./images/story-ocean/image4.jpg','南方澳海洋工作坊活動紀錄'],['./images/story-ocean/image5.jpg','南方澳漁港風景'],['./images/story-ocean/image6.jpg','長輩展示完成的作品'],['./images/story-ocean/image7.jpg','學員與志工一起創作']]};
const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),tag=document.getElementById('modalTag'),date=document.getElementById('modalDate'),deck=document.getElementById('modalDeck'),content=document.getElementById('modalContent'),close=document.getElementById('close');let priorFocus=null;
function hideModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(priorFocus)priorFocus.focus()}
document.querySelectorAll('[data-story]').forEach(btn=>btn.addEventListener('click',()=>{const s=stories[btn.dataset.story];if(!s)return;priorFocus=btn;tag.textContent=s.tag;date.textContent=s.date;title.textContent=s.title;deck.textContent=s.deck;content.innerHTML=s.body;const pics=galleries[btn.dataset.story];if(pics){const figures=pics.map(p=>"<figure><img src=\""+p[0]+"\" alt=\""+p[1]+"\" loading=\"lazy\"><figcaption>"+p[1]+"</figcaption></figure>").join("");content.insertAdjacentHTML("beforeend","<div class=\"photo-gallery\" aria-label=\"課堂照片\">"+figures+"</div>")}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');close.focus()}));
close.addEventListener('click',hideModal);modal.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))hideModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))hideModal()});
const toggle=document.getElementById('toggle'),nav=document.getElementById('nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'關閉導覽':'開啟導覽')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));


